// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwiVTONELEysyHbMUBxq_qpxllk6ejguo',
    appId: '1:1029635033542:web:86e054ead385c9293dcac7',
    messagingSenderId: '1029635033542',
    projectId: 'real-time-chat-app-eda9f',
    authDomain: 'real-time-chat-app-eda9f.firebaseapp.com',
    storageBucket: 'real-time-chat-app-eda9f.firebasestorage.app',
    measurementId: 'G-XV7DVKYB3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SU9eufUb3nGgqPgVEvZ063PsakjEr-I',
    appId: '1:1029635033542:android:420c9c7858fd824c3dcac7',
    messagingSenderId: '1029635033542',
    projectId: 'real-time-chat-app-eda9f',
    storageBucket: 'real-time-chat-app-eda9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuorBeWfIcJJKCc69psIGqnWyAfakxbrQ',
    appId: '1:1029635033542:ios:67b5a18e3e42b0d93dcac7',
    messagingSenderId: '1029635033542',
    projectId: 'real-time-chat-app-eda9f',
    storageBucket: 'real-time-chat-app-eda9f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuorBeWfIcJJKCc69psIGqnWyAfakxbrQ',
    appId: '1:1029635033542:ios:67b5a18e3e42b0d93dcac7',
    messagingSenderId: '1029635033542',
    projectId: 'real-time-chat-app-eda9f',
    storageBucket: 'real-time-chat-app-eda9f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwiVTONELEysyHbMUBxq_qpxllk6ejguo',
    appId: '1:1029635033542:web:4aaf89f02b1e8ed63dcac7',
    messagingSenderId: '1029635033542',
    projectId: 'real-time-chat-app-eda9f',
    authDomain: 'real-time-chat-app-eda9f.firebaseapp.com',
    storageBucket: 'real-time-chat-app-eda9f.firebasestorage.app',
    measurementId: 'G-47LHW0SGHE',
  );
}
